# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='General.proto',
  package='pb_sa',
  serialized_pb='\n\rGeneral.proto\x12\x05pb_sa\"d\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x02(\x05\x12(\n\x0crequest_type\x18\x02 \x01(\x0e\x32\x12.pb_sa.RequestType\x12\x11\n\ttimestamp\x18\x03 \x01(\x05*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"c\n\rSearchRequest\x12\x10\n\x08\x63lientid\x18\x03 \x02(\x05\x12\x14\n\x0chops_to_live\x18\x04 \x01(\x05\x12\x13\n\x0b\x66ingerprint\x18\x05 \x02(\x0c\x12\x15\n\roriginal_peer\x18\x06 \x01(\t\"L\n\x08PeerData\x12\x14\n\x0cpeer_address\x18\x01 \x02(\t\x12\x11\n\tclient_id\x18\x02 \x02(\x05\x12\x17\n\x0fnumber_of_songs\x18\x03 \x01(\x05\"_\n\x08SongData\x12\x11\n\tsong_name\x18\x01 \x02(\t\x12\x13\n\x0b\x61rtist_name\x18\x02 \x02(\t\x12\x12\n\nalbum_name\x18\x03 \x02(\t\x12\x17\n\x0f\x43onfidenceLevel\x18\x04 \x01(\x01\"#\n\x0e\x41\x64\x64SongRequest\x12\x11\n\tfile_path\x18\x01 \x02(\t*\xe0\x03\n\x0bRequestType\x12\x19\n\x15\x41RE_YOU_ALIVE_REQUEST\x10\x64\x12\x1a\n\x16\x41RE_YOU_ALIVE_RESPONSE\x10\x65\x12\x12\n\x0eSEARCH_REQUEST\x10\x66\x12\x10\n\x0cSEARCH_ABORT\x10g\x12\x15\n\x11SEARCH_SUCCESFULL\x10h\x12!\n\x1cMONITORING_GET_PEERS_REQUEST\x10\xc8\x01\x12\"\n\x1dMONITORING_GET_PEERS_RESPONSE\x10\xc9\x01\x12*\n%MONITORING_REQUESTS_PROCESSED_REQUEST\x10\xca\x01\x12+\n&MONITORING_REQUESTS_PROCESSED_RESPONSE\x10\xcb\x01\x12\x1a\n\x15REGISTER_PEER_REQUEST\x10\xad\x02\x12\x1b\n\x16REGISTER_PEER_RESPONSE\x10\xae\x02\x12\x16\n\x11\x42OOTSTRAP_REQUEST\x10\xaf\x02\x12\x17\n\x12\x42OOTSTRAP_RESPONSE\x10\xb0\x02\x12\x16\n\x11PEER_DEAD_REQUEST\x10\xb1\x02\x12\x1c\n\x17VALIDATE_SEARCH_REQUEST\x10\xb2\x02\x12\x1d\n\x18VALIDATE_SEARCH_RESPONSE\x10\xb3\x02*J\n\x14ValidateSearchStatus\x12\r\n\tSEARCH_OK\x10\x00\x12\x11\n\rSEARCH_DENIED\x10\x01\x12\x10\n\x0cSEARCH_ERROR\x10\x02*8\n\x0cSearchStatus\x12\t\n\x05\x46OUND\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x0e\n\nPROCESSING\x10\x02*5\n\x16PeerRegistrationStatus\x12\x0b\n\x07PEER_OK\x10\x00\x12\x0e\n\nPEER_ERROR\x10\x01\x42,\n*at.ac.tuwien.software.architectures.ws2012')

_REQUESTTYPE = descriptor.EnumDescriptor(
  name='RequestType',
  full_name='pb_sa.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ARE_YOU_ALIVE_REQUEST', index=0, number=100,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARE_YOU_ALIVE_RESPONSE', index=1, number=101,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SEARCH_REQUEST', index=2, number=102,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SEARCH_ABORT', index=3, number=103,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SEARCH_SUCCESFULL', index=4, number=104,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MONITORING_GET_PEERS_REQUEST', index=5, number=200,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MONITORING_GET_PEERS_RESPONSE', index=6, number=201,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MONITORING_REQUESTS_PROCESSED_REQUEST', index=7, number=202,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MONITORING_REQUESTS_PROCESSED_RESPONSE', index=8, number=203,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REGISTER_PEER_REQUEST', index=9, number=301,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REGISTER_PEER_RESPONSE', index=10, number=302,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BOOTSTRAP_REQUEST', index=11, number=303,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BOOTSTRAP_RESPONSE', index=12, number=304,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PEER_DEAD_REQUEST', index=13, number=305,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALIDATE_SEARCH_REQUEST', index=14, number=306,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VALIDATE_SEARCH_RESPONSE', index=15, number=307,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=440,
  serialized_end=920,
)


_VALIDATESEARCHSTATUS = descriptor.EnumDescriptor(
  name='ValidateSearchStatus',
  full_name='pb_sa.ValidateSearchStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SEARCH_OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SEARCH_DENIED', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SEARCH_ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=922,
  serialized_end=996,
)


_SEARCHSTATUS = descriptor.EnumDescriptor(
  name='SearchStatus',
  full_name='pb_sa.SearchStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FOUND', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=998,
  serialized_end=1054,
)


_PEERREGISTRATIONSTATUS = descriptor.EnumDescriptor(
  name='PeerRegistrationStatus',
  full_name='pb_sa.PeerRegistrationStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PEER_OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PEER_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1056,
  serialized_end=1109,
)


ARE_YOU_ALIVE_REQUEST = 100
ARE_YOU_ALIVE_RESPONSE = 101
SEARCH_REQUEST = 102
SEARCH_ABORT = 103
SEARCH_SUCCESFULL = 104
MONITORING_GET_PEERS_REQUEST = 200
MONITORING_GET_PEERS_RESPONSE = 201
MONITORING_REQUESTS_PROCESSED_REQUEST = 202
MONITORING_REQUESTS_PROCESSED_RESPONSE = 203
REGISTER_PEER_REQUEST = 301
REGISTER_PEER_RESPONSE = 302
BOOTSTRAP_REQUEST = 303
BOOTSTRAP_RESPONSE = 304
PEER_DEAD_REQUEST = 305
VALIDATE_SEARCH_REQUEST = 306
VALIDATE_SEARCH_RESPONSE = 307
SEARCH_OK = 0
SEARCH_DENIED = 1
SEARCH_ERROR = 2
FOUND = 0
NOT_FOUND = 1
PROCESSING = 2
PEER_OK = 0
PEER_ERROR = 1



_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='pb_sa.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_id', full_name='pb_sa.Request.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request_type', full_name='pb_sa.Request.request_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='pb_sa.Request.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  serialized_start=24,
  serialized_end=124,
)


_SEARCHREQUEST = descriptor.Descriptor(
  name='SearchRequest',
  full_name='pb_sa.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clientid', full_name='pb_sa.SearchRequest.clientid', index=0,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hops_to_live', full_name='pb_sa.SearchRequest.hops_to_live', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fingerprint', full_name='pb_sa.SearchRequest.fingerprint', index=2,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='original_peer', full_name='pb_sa.SearchRequest.original_peer', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=225,
)


_PEERDATA = descriptor.Descriptor(
  name='PeerData',
  full_name='pb_sa.PeerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='peer_address', full_name='pb_sa.PeerData.peer_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_id', full_name='pb_sa.PeerData.client_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='number_of_songs', full_name='pb_sa.PeerData.number_of_songs', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=303,
)


_SONGDATA = descriptor.Descriptor(
  name='SongData',
  full_name='pb_sa.SongData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='song_name', full_name='pb_sa.SongData.song_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='artist_name', full_name='pb_sa.SongData.artist_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='album_name', full_name='pb_sa.SongData.album_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ConfidenceLevel', full_name='pb_sa.SongData.ConfidenceLevel', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=305,
  serialized_end=400,
)


_ADDSONGREQUEST = descriptor.Descriptor(
  name='AddSongRequest',
  full_name='pb_sa.AddSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='file_path', full_name='pb_sa.AddSongRequest.file_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=402,
  serialized_end=437,
)

_REQUEST.fields_by_name['request_type'].enum_type = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['PeerData'] = _PEERDATA
DESCRIPTOR.message_types_by_name['SongData'] = _SONGDATA
DESCRIPTOR.message_types_by_name['AddSongRequest'] = _ADDSONGREQUEST

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.Request)

class SearchRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHREQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.SearchRequest)

class PeerData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEERDATA
  
  # @@protoc_insertion_point(class_scope:pb_sa.PeerData)

class SongData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SONGDATA
  
  # @@protoc_insertion_point(class_scope:pb_sa.SongData)

class AddSongRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSONGREQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.AddSongRequest)

# @@protoc_insertion_point(module_scope)
