# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Search.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import general_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Search.proto',
  package='',
  serialized_pb='\n\x0cSearch.proto\x1a\rgeneral.proto\"?\n\x15ValidateSearchRequest\x12&\n\x0esearch_request\x18\x01 \x02(\x0b\x32\x0e.SearchRequest\"\x94\x01\n\x16RegisterSearchResponse\x12\x43\n\rsearch_status\x18\x01 \x02(\x0e\x32,.RegisterSearchResponse.RegisterSearchStatus\"5\n\x14RegisterSearchStatus\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x44\x45NIED\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"!\n\x0bSearchAbort\x12\x12\n\nrequest_id\x18\x01 \x02(\x05\"l\n\x10SearchSuccessful\x12&\n\x0esearch_request\x18\x01 \x02(\x0b\x32\x0e.SearchRequest\x12\x16\n\x0e\x66ounder_peerid\x18\x02 \x02(\x05\x12\x18\n\x10\x66ounder_clientid\x18\x03 \x02(\x05\"B\n\x0eSearchResponse\x12\x12\n\nrequest_id\x18\x01 \x02(\x05\x12\x1c\n\tsong_data\x18\x02 \x01(\x0b\x32\t.SongData')



_REGISTERSEARCHRESPONSE_REGISTERSEARCHSTATUS = _descriptor.EnumDescriptor(
  name='RegisterSearchStatus',
  full_name='RegisterSearchResponse.RegisterSearchStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENIED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=192,
  serialized_end=245,
)


_VALIDATESEARCHREQUEST = _descriptor.Descriptor(
  name='ValidateSearchRequest',
  full_name='ValidateSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_request', full_name='ValidateSearchRequest.search_request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=94,
)


_REGISTERSEARCHRESPONSE = _descriptor.Descriptor(
  name='RegisterSearchResponse',
  full_name='RegisterSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_status', full_name='RegisterSearchResponse.search_status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTERSEARCHRESPONSE_REGISTERSEARCHSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=245,
)


_SEARCHABORT = _descriptor.Descriptor(
  name='SearchAbort',
  full_name='SearchAbort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='SearchAbort.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=247,
  serialized_end=280,
)


_SEARCHSUCCESSFUL = _descriptor.Descriptor(
  name='SearchSuccessful',
  full_name='SearchSuccessful',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_request', full_name='SearchSuccessful.search_request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='founder_peerid', full_name='SearchSuccessful.founder_peerid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='founder_clientid', full_name='SearchSuccessful.founder_clientid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=282,
  serialized_end=390,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='SearchResponse.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='song_data', full_name='SearchResponse.song_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=392,
  serialized_end=458,
)

_VALIDATESEARCHREQUEST.fields_by_name['search_request'].message_type = general_pb2._SEARCHREQUEST
_REGISTERSEARCHRESPONSE.fields_by_name['search_status'].enum_type = _REGISTERSEARCHRESPONSE_REGISTERSEARCHSTATUS
_REGISTERSEARCHRESPONSE_REGISTERSEARCHSTATUS.containing_type = _REGISTERSEARCHRESPONSE;
_SEARCHSUCCESSFUL.fields_by_name['search_request'].message_type = general_pb2._SEARCHREQUEST
_SEARCHRESPONSE.fields_by_name['song_data'].message_type = general_pb2._SONGDATA
DESCRIPTOR.message_types_by_name['ValidateSearchRequest'] = _VALIDATESEARCHREQUEST
DESCRIPTOR.message_types_by_name['RegisterSearchResponse'] = _REGISTERSEARCHRESPONSE
DESCRIPTOR.message_types_by_name['SearchAbort'] = _SEARCHABORT
DESCRIPTOR.message_types_by_name['SearchSuccessful'] = _SEARCHSUCCESSFUL
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE

class ValidateSearchRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALIDATESEARCHREQUEST

  # @@protoc_insertion_point(class_scope:ValidateSearchRequest)

class RegisterSearchResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERSEARCHRESPONSE

  # @@protoc_insertion_point(class_scope:RegisterSearchResponse)

class SearchAbort(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHABORT

  # @@protoc_insertion_point(class_scope:SearchAbort)

class SearchSuccessful(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHSUCCESSFUL

  # @@protoc_insertion_point(class_scope:SearchSuccessful)

class SearchResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHRESPONSE

  # @@protoc_insertion_point(class_scope:SearchResponse)


# @@protoc_insertion_point(module_scope)
