# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import General_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='server.proto',
  package='pb_sa',
  serialized_pb='\n\x0cserver.proto\x12\x05pb_sa\x1a\rGeneral.proto\">\n\x13RegisterPeerRequest\x12\x14\n\x0cpeer_address\x18\x01 \x02(\t\x12\x11\n\tclient_id\x18\x02 \x02(\x05\"[\n\x14RegisterPeerResponse\x12\x14\n\x0cpeer_address\x18\x01 \x01(\t\x12-\n\x06status\x18\x02 \x01(\x0e\x32\x1d.pb_sa.PeerRegistrationStatus\")\n\x10\x42ootstrapRequest\x12\x15\n\rnumberOfPeers\x18\x01 \x02(\x05\"2\n\x11\x42ootstrapResponse\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.pb_sa.PeerData\"+\n\x0fPeerDeadRequest\x12\x18\n\x10\x64\x65stination_peer\x18\x01 \x02(\t\"E\n\x15ValidateSearchRequest\x12,\n\x0esearch_request\x18\x01 \x02(\x0b\x32\x14.pb_sa.SearchRequest\"z\n\x16ValidateSearchResponse\x12\x32\n\rsearch_status\x18\x01 \x02(\x0e\x32\x1b.pb_sa.ValidateSearchStatus\x12,\n\x0esearch_request\x18\x02 \x02(\x0b\x32\x14.pb_sa.SearchRequest:J\n\x15register_peer_request\x12\x0e.pb_sa.Request\x18\xac\x02 \x01(\x0b\x32\x1a.pb_sa.RegisterPeerRequest:L\n\x16register_peer_response\x12\x0e.pb_sa.Request\x18\xad\x02 \x01(\x0b\x32\x1b.pb_sa.RegisterPeerResponse:C\n\x11\x62ootstrap_request\x12\x0e.pb_sa.Request\x18\xae\x02 \x01(\x0b\x32\x17.pb_sa.BootstrapRequest:E\n\x12\x62ootstrap_response\x12\x0e.pb_sa.Request\x18\xaf\x02 \x01(\x0b\x32\x18.pb_sa.BootstrapResponse:B\n\x11peer_dead_request\x12\x0e.pb_sa.Request\x18\xb0\x02 \x01(\x0b\x32\x16.pb_sa.PeerDeadRequest:N\n\x17validate_search_request\x12\x0e.pb_sa.Request\x18\xb1\x02 \x01(\x0b\x32\x1c.pb_sa.ValidateSearchRequest:P\n\x18validate_search_response\x12\x0e.pb_sa.Request\x18\xb2\x02 \x01(\x0b\x32\x1d.pb_sa.ValidateSearchResponseB,\n*at.ac.tuwien.software.architectures.ws2012')


REGISTER_PEER_REQUEST_FIELD_NUMBER = 300
register_peer_request = descriptor.FieldDescriptor(
  name='register_peer_request', full_name='pb_sa.register_peer_request', index=0,
  number=300, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
REGISTER_PEER_RESPONSE_FIELD_NUMBER = 301
register_peer_response = descriptor.FieldDescriptor(
  name='register_peer_response', full_name='pb_sa.register_peer_response', index=1,
  number=301, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
BOOTSTRAP_REQUEST_FIELD_NUMBER = 302
bootstrap_request = descriptor.FieldDescriptor(
  name='bootstrap_request', full_name='pb_sa.bootstrap_request', index=2,
  number=302, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
BOOTSTRAP_RESPONSE_FIELD_NUMBER = 303
bootstrap_response = descriptor.FieldDescriptor(
  name='bootstrap_response', full_name='pb_sa.bootstrap_response', index=3,
  number=303, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
PEER_DEAD_REQUEST_FIELD_NUMBER = 304
peer_dead_request = descriptor.FieldDescriptor(
  name='peer_dead_request', full_name='pb_sa.peer_dead_request', index=4,
  number=304, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
VALIDATE_SEARCH_REQUEST_FIELD_NUMBER = 305
validate_search_request = descriptor.FieldDescriptor(
  name='validate_search_request', full_name='pb_sa.validate_search_request', index=5,
  number=305, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
VALIDATE_SEARCH_RESPONSE_FIELD_NUMBER = 306
validate_search_response = descriptor.FieldDescriptor(
  name='validate_search_response', full_name='pb_sa.validate_search_response', index=6,
  number=306, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_REGISTERPEERREQUEST = descriptor.Descriptor(
  name='RegisterPeerRequest',
  full_name='pb_sa.RegisterPeerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='peer_address', full_name='pb_sa.RegisterPeerRequest.peer_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_id', full_name='pb_sa.RegisterPeerRequest.client_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=100,
)


_REGISTERPEERRESPONSE = descriptor.Descriptor(
  name='RegisterPeerResponse',
  full_name='pb_sa.RegisterPeerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='peer_address', full_name='pb_sa.RegisterPeerResponse.peer_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='pb_sa.RegisterPeerResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=193,
)


_BOOTSTRAPREQUEST = descriptor.Descriptor(
  name='BootstrapRequest',
  full_name='pb_sa.BootstrapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='numberOfPeers', full_name='pb_sa.BootstrapRequest.numberOfPeers', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=195,
  serialized_end=236,
)


_BOOTSTRAPRESPONSE = descriptor.Descriptor(
  name='BootstrapResponse',
  full_name='pb_sa.BootstrapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='pb_sa.BootstrapResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=238,
  serialized_end=288,
)


_PEERDEADREQUEST = descriptor.Descriptor(
  name='PeerDeadRequest',
  full_name='pb_sa.PeerDeadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='destination_peer', full_name='pb_sa.PeerDeadRequest.destination_peer', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=333,
)


_VALIDATESEARCHREQUEST = descriptor.Descriptor(
  name='ValidateSearchRequest',
  full_name='pb_sa.ValidateSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='search_request', full_name='pb_sa.ValidateSearchRequest.search_request', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=335,
  serialized_end=404,
)


_VALIDATESEARCHRESPONSE = descriptor.Descriptor(
  name='ValidateSearchResponse',
  full_name='pb_sa.ValidateSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='search_status', full_name='pb_sa.ValidateSearchResponse.search_status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='search_request', full_name='pb_sa.ValidateSearchResponse.search_request', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=406,
  serialized_end=528,
)

_REGISTERPEERRESPONSE.fields_by_name['status'].enum_type = General_pb2._PEERREGISTRATIONSTATUS
_BOOTSTRAPRESPONSE.fields_by_name['data'].message_type = General_pb2._PEERDATA
_VALIDATESEARCHREQUEST.fields_by_name['search_request'].message_type = General_pb2._SEARCHREQUEST
_VALIDATESEARCHRESPONSE.fields_by_name['search_status'].enum_type = General_pb2._VALIDATESEARCHSTATUS
_VALIDATESEARCHRESPONSE.fields_by_name['search_request'].message_type = General_pb2._SEARCHREQUEST
DESCRIPTOR.message_types_by_name['RegisterPeerRequest'] = _REGISTERPEERREQUEST
DESCRIPTOR.message_types_by_name['RegisterPeerResponse'] = _REGISTERPEERRESPONSE
DESCRIPTOR.message_types_by_name['BootstrapRequest'] = _BOOTSTRAPREQUEST
DESCRIPTOR.message_types_by_name['BootstrapResponse'] = _BOOTSTRAPRESPONSE
DESCRIPTOR.message_types_by_name['PeerDeadRequest'] = _PEERDEADREQUEST
DESCRIPTOR.message_types_by_name['ValidateSearchRequest'] = _VALIDATESEARCHREQUEST
DESCRIPTOR.message_types_by_name['ValidateSearchResponse'] = _VALIDATESEARCHRESPONSE

class RegisterPeerRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERPEERREQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.RegisterPeerRequest)

class RegisterPeerResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERPEERRESPONSE
  
  # @@protoc_insertion_point(class_scope:pb_sa.RegisterPeerResponse)

class BootstrapRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOTSTRAPREQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.BootstrapRequest)

class BootstrapResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOTSTRAPRESPONSE
  
  # @@protoc_insertion_point(class_scope:pb_sa.BootstrapResponse)

class PeerDeadRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEERDEADREQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.PeerDeadRequest)

class ValidateSearchRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALIDATESEARCHREQUEST
  
  # @@protoc_insertion_point(class_scope:pb_sa.ValidateSearchRequest)

class ValidateSearchResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VALIDATESEARCHRESPONSE
  
  # @@protoc_insertion_point(class_scope:pb_sa.ValidateSearchResponse)

register_peer_request.message_type = _REGISTERPEERREQUEST
General_pb2.Request.RegisterExtension(register_peer_request)
register_peer_response.message_type = _REGISTERPEERRESPONSE
General_pb2.Request.RegisterExtension(register_peer_response)
bootstrap_request.message_type = _BOOTSTRAPREQUEST
General_pb2.Request.RegisterExtension(bootstrap_request)
bootstrap_response.message_type = _BOOTSTRAPRESPONSE
General_pb2.Request.RegisterExtension(bootstrap_response)
peer_dead_request.message_type = _PEERDEADREQUEST
General_pb2.Request.RegisterExtension(peer_dead_request)
validate_search_request.message_type = _VALIDATESEARCHREQUEST
General_pb2.Request.RegisterExtension(validate_search_request)
validate_search_response.message_type = _VALIDATESEARCHRESPONSE
General_pb2.Request.RegisterExtension(validate_search_response)
# @@protoc_insertion_point(module_scope)
