// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: General.proto

package at.ac.tuwien.software.architectures.ws2012;

public final class General {
  private General() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ValidateSearchStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    SEARCH_OK(0, 0),
    SEARCH_DENIED(1, 1),
    SEARCH_ERROR(2, 2),
    ;
    
    public static final int SEARCH_OK_VALUE = 0;
    public static final int SEARCH_DENIED_VALUE = 1;
    public static final int SEARCH_ERROR_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static ValidateSearchStatus valueOf(int value) {
      switch (value) {
        case 0: return SEARCH_OK;
        case 1: return SEARCH_DENIED;
        case 2: return SEARCH_ERROR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ValidateSearchStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ValidateSearchStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ValidateSearchStatus>() {
            public ValidateSearchStatus findValueByNumber(int number) {
              return ValidateSearchStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ValidateSearchStatus[] VALUES = {
      SEARCH_OK, SEARCH_DENIED, SEARCH_ERROR, 
    };
    
    public static ValidateSearchStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ValidateSearchStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:pb_sa.ValidateSearchStatus)
  }
  
  public enum SearchStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    FOUND(0, 0),
    NOT_FOUND(1, 1),
    PROCESSING(2, 2),
    ;
    
    public static final int FOUND_VALUE = 0;
    public static final int NOT_FOUND_VALUE = 1;
    public static final int PROCESSING_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static SearchStatus valueOf(int value) {
      switch (value) {
        case 0: return FOUND;
        case 1: return NOT_FOUND;
        case 2: return PROCESSING;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SearchStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SearchStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SearchStatus>() {
            public SearchStatus findValueByNumber(int number) {
              return SearchStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final SearchStatus[] VALUES = {
      FOUND, NOT_FOUND, PROCESSING, 
    };
    
    public static SearchStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private SearchStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:pb_sa.SearchStatus)
  }
  
  public enum PeerRegistrationStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    PEER_OK(0, 0),
    PEER_ERROR(1, 1),
    ;
    
    public static final int PEER_OK_VALUE = 0;
    public static final int PEER_ERROR_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static PeerRegistrationStatus valueOf(int value) {
      switch (value) {
        case 0: return PEER_OK;
        case 1: return PEER_ERROR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PeerRegistrationStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PeerRegistrationStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PeerRegistrationStatus>() {
            public PeerRegistrationStatus findValueByNumber(int number) {
              return PeerRegistrationStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.getDescriptor().getEnumTypes().get(2);
    }
    
    private static final PeerRegistrationStatus[] VALUES = {
      PEER_OK, PEER_ERROR, 
    };
    
    public static PeerRegistrationStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private PeerRegistrationStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:pb_sa.PeerRegistrationStatus)
  }
  
  public interface SearchRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 request_id = 1;
    boolean hasRequestId();
    int getRequestId();
    
    // required int32 timestamp = 2;
    boolean hasTimestamp();
    int getTimestamp();
    
    // required int32 clientid = 3;
    boolean hasClientid();
    int getClientid();
    
    // optional int32 hops_to_live = 4;
    boolean hasHopsToLive();
    int getHopsToLive();
    
    // required bytes fingerprint = 5;
    boolean hasFingerprint();
    com.google.protobuf.ByteString getFingerprint();
    
    // optional string original_peer = 6;
    boolean hasOriginalPeer();
    String getOriginalPeer();
  }
  public static final class SearchRequest extends
      com.google.protobuf.GeneratedMessage
      implements SearchRequestOrBuilder {
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(Builder builder) {
      super(builder);
    }
    private SearchRequest(boolean noInit) {}
    
    private static final SearchRequest defaultInstance;
    public static SearchRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SearchRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SearchRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 request_id = 1;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private int requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRequestId() {
      return requestId_;
    }
    
    // required int32 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private int timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTimestamp() {
      return timestamp_;
    }
    
    // required int32 clientid = 3;
    public static final int CLIENTID_FIELD_NUMBER = 3;
    private int clientid_;
    public boolean hasClientid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getClientid() {
      return clientid_;
    }
    
    // optional int32 hops_to_live = 4;
    public static final int HOPS_TO_LIVE_FIELD_NUMBER = 4;
    private int hopsToLive_;
    public boolean hasHopsToLive() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getHopsToLive() {
      return hopsToLive_;
    }
    
    // required bytes fingerprint = 5;
    public static final int FINGERPRINT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString fingerprint_;
    public boolean hasFingerprint() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getFingerprint() {
      return fingerprint_;
    }
    
    // optional string original_peer = 6;
    public static final int ORIGINAL_PEER_FIELD_NUMBER = 6;
    private java.lang.Object originalPeer_;
    public boolean hasOriginalPeer() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getOriginalPeer() {
      java.lang.Object ref = originalPeer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          originalPeer_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOriginalPeerBytes() {
      java.lang.Object ref = originalPeer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        originalPeer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      requestId_ = 0;
      timestamp_ = 0;
      clientid_ = 0;
      hopsToLive_ = 0;
      fingerprint_ = com.google.protobuf.ByteString.EMPTY;
      originalPeer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFingerprint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, clientid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, hopsToLive_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, fingerprint_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getOriginalPeerBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clientid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, hopsToLive_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, fingerprint_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getOriginalPeerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(at.ac.tuwien.software.architectures.ws2012.General.SearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements at.ac.tuwien.software.architectures.ws2012.General.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SearchRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SearchRequest_fieldAccessorTable;
      }
      
      // Construct using at.ac.tuwien.software.architectures.ws2012.General.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        hopsToLive_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        fingerprint_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        originalPeer_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.SearchRequest.getDescriptor();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.SearchRequest getDefaultInstanceForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.SearchRequest.getDefaultInstance();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.SearchRequest build() {
        at.ac.tuwien.software.architectures.ws2012.General.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private at.ac.tuwien.software.architectures.ws2012.General.SearchRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        at.ac.tuwien.software.architectures.ws2012.General.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.SearchRequest buildPartial() {
        at.ac.tuwien.software.architectures.ws2012.General.SearchRequest result = new at.ac.tuwien.software.architectures.ws2012.General.SearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientid_ = clientid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hopsToLive_ = hopsToLive_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fingerprint_ = fingerprint_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.originalPeer_ = originalPeer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.ac.tuwien.software.architectures.ws2012.General.SearchRequest) {
          return mergeFrom((at.ac.tuwien.software.architectures.ws2012.General.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(at.ac.tuwien.software.architectures.ws2012.General.SearchRequest other) {
        if (other == at.ac.tuwien.software.architectures.ws2012.General.SearchRequest.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasClientid()) {
          setClientid(other.getClientid());
        }
        if (other.hasHopsToLive()) {
          setHopsToLive(other.getHopsToLive());
        }
        if (other.hasFingerprint()) {
          setFingerprint(other.getFingerprint());
        }
        if (other.hasOriginalPeer()) {
          setOriginalPeer(other.getOriginalPeer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasClientid()) {
          
          return false;
        }
        if (!hasFingerprint()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clientid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hopsToLive_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              fingerprint_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              originalPeer_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 request_id = 1;
      private int requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 timestamp = 2;
      private int timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 clientid = 3;
      private int clientid_ ;
      public boolean hasClientid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getClientid() {
        return clientid_;
      }
      public Builder setClientid(int value) {
        bitField0_ |= 0x00000004;
        clientid_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientid_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 hops_to_live = 4;
      private int hopsToLive_ ;
      public boolean hasHopsToLive() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getHopsToLive() {
        return hopsToLive_;
      }
      public Builder setHopsToLive(int value) {
        bitField0_ |= 0x00000008;
        hopsToLive_ = value;
        onChanged();
        return this;
      }
      public Builder clearHopsToLive() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hopsToLive_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes fingerprint = 5;
      private com.google.protobuf.ByteString fingerprint_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasFingerprint() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getFingerprint() {
        return fingerprint_;
      }
      public Builder setFingerprint(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fingerprint_ = value;
        onChanged();
        return this;
      }
      public Builder clearFingerprint() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fingerprint_ = getDefaultInstance().getFingerprint();
        onChanged();
        return this;
      }
      
      // optional string original_peer = 6;
      private java.lang.Object originalPeer_ = "";
      public boolean hasOriginalPeer() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getOriginalPeer() {
        java.lang.Object ref = originalPeer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          originalPeer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOriginalPeer(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        originalPeer_ = value;
        onChanged();
        return this;
      }
      public Builder clearOriginalPeer() {
        bitField0_ = (bitField0_ & ~0x00000020);
        originalPeer_ = getDefaultInstance().getOriginalPeer();
        onChanged();
        return this;
      }
      void setOriginalPeer(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        originalPeer_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:pb_sa.SearchRequest)
    }
    
    static {
      defaultInstance = new SearchRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb_sa.SearchRequest)
  }
  
  public interface PeerDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string peer_address = 1;
    boolean hasPeerAddress();
    String getPeerAddress();
    
    // required int32 client_id = 2;
    boolean hasClientId();
    int getClientId();
    
    // optional int32 number_of_songs = 3;
    boolean hasNumberOfSongs();
    int getNumberOfSongs();
  }
  public static final class PeerData extends
      com.google.protobuf.GeneratedMessage
      implements PeerDataOrBuilder {
    // Use PeerData.newBuilder() to construct.
    private PeerData(Builder builder) {
      super(builder);
    }
    private PeerData(boolean noInit) {}
    
    private static final PeerData defaultInstance;
    public static PeerData getDefaultInstance() {
      return defaultInstance;
    }
    
    public PeerData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_PeerData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_PeerData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string peer_address = 1;
    public static final int PEER_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object peerAddress_;
    public boolean hasPeerAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPeerAddress() {
      java.lang.Object ref = peerAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          peerAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPeerAddressBytes() {
      java.lang.Object ref = peerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        peerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 client_id = 2;
    public static final int CLIENT_ID_FIELD_NUMBER = 2;
    private int clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getClientId() {
      return clientId_;
    }
    
    // optional int32 number_of_songs = 3;
    public static final int NUMBER_OF_SONGS_FIELD_NUMBER = 3;
    private int numberOfSongs_;
    public boolean hasNumberOfSongs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNumberOfSongs() {
      return numberOfSongs_;
    }
    
    private void initFields() {
      peerAddress_ = "";
      clientId_ = 0;
      numberOfSongs_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPeerAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPeerAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, numberOfSongs_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPeerAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numberOfSongs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.PeerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(at.ac.tuwien.software.architectures.ws2012.General.PeerData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements at.ac.tuwien.software.architectures.ws2012.General.PeerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_PeerData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_PeerData_fieldAccessorTable;
      }
      
      // Construct using at.ac.tuwien.software.architectures.ws2012.General.PeerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        peerAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        numberOfSongs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.PeerData.getDescriptor();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.PeerData getDefaultInstanceForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.PeerData.getDefaultInstance();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.PeerData build() {
        at.ac.tuwien.software.architectures.ws2012.General.PeerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private at.ac.tuwien.software.architectures.ws2012.General.PeerData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        at.ac.tuwien.software.architectures.ws2012.General.PeerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.PeerData buildPartial() {
        at.ac.tuwien.software.architectures.ws2012.General.PeerData result = new at.ac.tuwien.software.architectures.ws2012.General.PeerData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.peerAddress_ = peerAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.numberOfSongs_ = numberOfSongs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.ac.tuwien.software.architectures.ws2012.General.PeerData) {
          return mergeFrom((at.ac.tuwien.software.architectures.ws2012.General.PeerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(at.ac.tuwien.software.architectures.ws2012.General.PeerData other) {
        if (other == at.ac.tuwien.software.architectures.ws2012.General.PeerData.getDefaultInstance()) return this;
        if (other.hasPeerAddress()) {
          setPeerAddress(other.getPeerAddress());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasNumberOfSongs()) {
          setNumberOfSongs(other.getNumberOfSongs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPeerAddress()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              peerAddress_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              numberOfSongs_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string peer_address = 1;
      private java.lang.Object peerAddress_ = "";
      public boolean hasPeerAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPeerAddress() {
        java.lang.Object ref = peerAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          peerAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPeerAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        peerAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearPeerAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        peerAddress_ = getDefaultInstance().getPeerAddress();
        onChanged();
        return this;
      }
      void setPeerAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        peerAddress_ = value;
        onChanged();
      }
      
      // required int32 client_id = 2;
      private int clientId_ ;
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getClientId() {
        return clientId_;
      }
      public Builder setClientId(int value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 number_of_songs = 3;
      private int numberOfSongs_ ;
      public boolean hasNumberOfSongs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNumberOfSongs() {
        return numberOfSongs_;
      }
      public Builder setNumberOfSongs(int value) {
        bitField0_ |= 0x00000004;
        numberOfSongs_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumberOfSongs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numberOfSongs_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pb_sa.PeerData)
    }
    
    static {
      defaultInstance = new PeerData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb_sa.PeerData)
  }
  
  public interface SongDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string song_name = 1;
    boolean hasSongName();
    String getSongName();
    
    // required string artist_name = 2;
    boolean hasArtistName();
    String getArtistName();
    
    // required string album_name = 3;
    boolean hasAlbumName();
    String getAlbumName();
    
    // optional double ConfidenceLevel = 4;
    boolean hasConfidenceLevel();
    double getConfidenceLevel();
  }
  public static final class SongData extends
      com.google.protobuf.GeneratedMessage
      implements SongDataOrBuilder {
    // Use SongData.newBuilder() to construct.
    private SongData(Builder builder) {
      super(builder);
    }
    private SongData(boolean noInit) {}
    
    private static final SongData defaultInstance;
    public static SongData getDefaultInstance() {
      return defaultInstance;
    }
    
    public SongData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SongData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SongData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string song_name = 1;
    public static final int SONG_NAME_FIELD_NUMBER = 1;
    private java.lang.Object songName_;
    public boolean hasSongName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSongName() {
      java.lang.Object ref = songName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          songName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSongNameBytes() {
      java.lang.Object ref = songName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        songName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string artist_name = 2;
    public static final int ARTIST_NAME_FIELD_NUMBER = 2;
    private java.lang.Object artistName_;
    public boolean hasArtistName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getArtistName() {
      java.lang.Object ref = artistName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          artistName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getArtistNameBytes() {
      java.lang.Object ref = artistName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        artistName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string album_name = 3;
    public static final int ALBUM_NAME_FIELD_NUMBER = 3;
    private java.lang.Object albumName_;
    public boolean hasAlbumName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAlbumName() {
      java.lang.Object ref = albumName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          albumName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAlbumNameBytes() {
      java.lang.Object ref = albumName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        albumName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double ConfidenceLevel = 4;
    public static final int CONFIDENCELEVEL_FIELD_NUMBER = 4;
    private double confidenceLevel_;
    public boolean hasConfidenceLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getConfidenceLevel() {
      return confidenceLevel_;
    }
    
    private void initFields() {
      songName_ = "";
      artistName_ = "";
      albumName_ = "";
      confidenceLevel_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSongName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArtistName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlbumName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSongNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getArtistNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAlbumNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, confidenceLevel_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSongNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getArtistNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAlbumNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, confidenceLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.SongData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(at.ac.tuwien.software.architectures.ws2012.General.SongData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements at.ac.tuwien.software.architectures.ws2012.General.SongDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SongData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_SongData_fieldAccessorTable;
      }
      
      // Construct using at.ac.tuwien.software.architectures.ws2012.General.SongData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        songName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        artistName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        albumName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        confidenceLevel_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.SongData.getDescriptor();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.SongData getDefaultInstanceForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.SongData.getDefaultInstance();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.SongData build() {
        at.ac.tuwien.software.architectures.ws2012.General.SongData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private at.ac.tuwien.software.architectures.ws2012.General.SongData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        at.ac.tuwien.software.architectures.ws2012.General.SongData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.SongData buildPartial() {
        at.ac.tuwien.software.architectures.ws2012.General.SongData result = new at.ac.tuwien.software.architectures.ws2012.General.SongData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.songName_ = songName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.artistName_ = artistName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.albumName_ = albumName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.confidenceLevel_ = confidenceLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.ac.tuwien.software.architectures.ws2012.General.SongData) {
          return mergeFrom((at.ac.tuwien.software.architectures.ws2012.General.SongData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(at.ac.tuwien.software.architectures.ws2012.General.SongData other) {
        if (other == at.ac.tuwien.software.architectures.ws2012.General.SongData.getDefaultInstance()) return this;
        if (other.hasSongName()) {
          setSongName(other.getSongName());
        }
        if (other.hasArtistName()) {
          setArtistName(other.getArtistName());
        }
        if (other.hasAlbumName()) {
          setAlbumName(other.getAlbumName());
        }
        if (other.hasConfidenceLevel()) {
          setConfidenceLevel(other.getConfidenceLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSongName()) {
          
          return false;
        }
        if (!hasArtistName()) {
          
          return false;
        }
        if (!hasAlbumName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              songName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              artistName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              albumName_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              confidenceLevel_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string song_name = 1;
      private java.lang.Object songName_ = "";
      public boolean hasSongName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSongName() {
        java.lang.Object ref = songName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          songName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSongName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        songName_ = value;
        onChanged();
        return this;
      }
      public Builder clearSongName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        songName_ = getDefaultInstance().getSongName();
        onChanged();
        return this;
      }
      void setSongName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        songName_ = value;
        onChanged();
      }
      
      // required string artist_name = 2;
      private java.lang.Object artistName_ = "";
      public boolean hasArtistName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getArtistName() {
        java.lang.Object ref = artistName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          artistName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setArtistName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artistName_ = value;
        onChanged();
        return this;
      }
      public Builder clearArtistName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        artistName_ = getDefaultInstance().getArtistName();
        onChanged();
        return this;
      }
      void setArtistName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        artistName_ = value;
        onChanged();
      }
      
      // required string album_name = 3;
      private java.lang.Object albumName_ = "";
      public boolean hasAlbumName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAlbumName() {
        java.lang.Object ref = albumName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          albumName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAlbumName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        albumName_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlbumName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        albumName_ = getDefaultInstance().getAlbumName();
        onChanged();
        return this;
      }
      void setAlbumName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        albumName_ = value;
        onChanged();
      }
      
      // optional double ConfidenceLevel = 4;
      private double confidenceLevel_ ;
      public boolean hasConfidenceLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getConfidenceLevel() {
        return confidenceLevel_;
      }
      public Builder setConfidenceLevel(double value) {
        bitField0_ |= 0x00000008;
        confidenceLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearConfidenceLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        confidenceLevel_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pb_sa.SongData)
    }
    
    static {
      defaultInstance = new SongData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb_sa.SongData)
  }
  
  public interface AddSongRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string file_path = 1;
    boolean hasFilePath();
    String getFilePath();
  }
  public static final class AddSongRequest extends
      com.google.protobuf.GeneratedMessage
      implements AddSongRequestOrBuilder {
    // Use AddSongRequest.newBuilder() to construct.
    private AddSongRequest(Builder builder) {
      super(builder);
    }
    private AddSongRequest(boolean noInit) {}
    
    private static final AddSongRequest defaultInstance;
    public static AddSongRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddSongRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_AddSongRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_AddSongRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string file_path = 1;
    public static final int FILE_PATH_FIELD_NUMBER = 1;
    private java.lang.Object filePath_;
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          filePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      filePath_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilePathBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilePathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements at.ac.tuwien.software.architectures.ws2012.General.AddSongRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_AddSongRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.ac.tuwien.software.architectures.ws2012.General.internal_static_pb_sa_AddSongRequest_fieldAccessorTable;
      }
      
      // Construct using at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        filePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest.getDescriptor();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest getDefaultInstanceForType() {
        return at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest.getDefaultInstance();
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest build() {
        at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest buildPartial() {
        at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest result = new at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filePath_ = filePath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest) {
          return mergeFrom((at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest other) {
        if (other == at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest.getDefaultInstance()) return this;
        if (other.hasFilePath()) {
          setFilePath(other.getFilePath());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFilePath()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filePath_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string file_path = 1;
      private java.lang.Object filePath_ = "";
      public boolean hasFilePath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFilePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearFilePath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      void setFilePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:pb_sa.AddSongRequest)
    }
    
    static {
      defaultInstance = new AddSongRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb_sa.AddSongRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_sa_SearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_sa_SearchRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_sa_PeerData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_sa_PeerData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_sa_SongData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_sa_SongData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_sa_AddSongRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_sa_AddSongRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGeneral.proto\022\005pb_sa\"\212\001\n\rSearchRequest" +
      "\022\022\n\nrequest_id\030\001 \002(\005\022\021\n\ttimestamp\030\002 \002(\005\022" +
      "\020\n\010clientid\030\003 \002(\005\022\024\n\014hops_to_live\030\004 \001(\005\022" +
      "\023\n\013fingerprint\030\005 \002(\014\022\025\n\roriginal_peer\030\006 " +
      "\001(\t\"L\n\010PeerData\022\024\n\014peer_address\030\001 \002(\t\022\021\n" +
      "\tclient_id\030\002 \002(\005\022\027\n\017number_of_songs\030\003 \001(" +
      "\005\"_\n\010SongData\022\021\n\tsong_name\030\001 \002(\t\022\023\n\013arti" +
      "st_name\030\002 \002(\t\022\022\n\nalbum_name\030\003 \002(\t\022\027\n\017Con" +
      "fidenceLevel\030\004 \001(\001\"#\n\016AddSongRequest\022\021\n\t" +
      "file_path\030\001 \002(\t*J\n\024ValidateSearchStatus\022",
      "\r\n\tSEARCH_OK\020\000\022\021\n\rSEARCH_DENIED\020\001\022\020\n\014SEA" +
      "RCH_ERROR\020\002*8\n\014SearchStatus\022\t\n\005FOUND\020\000\022\r" +
      "\n\tNOT_FOUND\020\001\022\016\n\nPROCESSING\020\002*5\n\026PeerReg" +
      "istrationStatus\022\013\n\007PEER_OK\020\000\022\016\n\nPEER_ERR" +
      "OR\020\001B,\n*at.ac.tuwien.software.architectu" +
      "res.ws2012"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pb_sa_SearchRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pb_sa_SearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_sa_SearchRequest_descriptor,
              new java.lang.String[] { "RequestId", "Timestamp", "Clientid", "HopsToLive", "Fingerprint", "OriginalPeer", },
              at.ac.tuwien.software.architectures.ws2012.General.SearchRequest.class,
              at.ac.tuwien.software.architectures.ws2012.General.SearchRequest.Builder.class);
          internal_static_pb_sa_PeerData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pb_sa_PeerData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_sa_PeerData_descriptor,
              new java.lang.String[] { "PeerAddress", "ClientId", "NumberOfSongs", },
              at.ac.tuwien.software.architectures.ws2012.General.PeerData.class,
              at.ac.tuwien.software.architectures.ws2012.General.PeerData.Builder.class);
          internal_static_pb_sa_SongData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_pb_sa_SongData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_sa_SongData_descriptor,
              new java.lang.String[] { "SongName", "ArtistName", "AlbumName", "ConfidenceLevel", },
              at.ac.tuwien.software.architectures.ws2012.General.SongData.class,
              at.ac.tuwien.software.architectures.ws2012.General.SongData.Builder.class);
          internal_static_pb_sa_AddSongRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_pb_sa_AddSongRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_sa_AddSongRequest_descriptor,
              new java.lang.String[] { "FilePath", },
              at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest.class,
              at.ac.tuwien.software.architectures.ws2012.General.AddSongRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
